version: '3.8'

services:
  db:
    image: "mysql:8"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - "db-data:/var/lib/mysql"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      JDBC_URL: "jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true"
      JDBC_USERNAME: ${DB_USER}
      JDBC_PASSWORD: ${DB_PASS}
      SPRING_PROFILES_ACTIVE: prd
      SERVER_PORT: 8080

volumes:
  db-data: