package com.tracelink.appsec.watchtower.core.module.scanner;

import com.tracelink.appsec.watchtower.core.rule.RuleDto;
import com.tracelink.appsec.watchtower.core.scan.code.CodeScanConfig;
import com.tracelink.appsec.watchtower.core.scan.code.report.CodeScanReport;

/**
 * The executor of a scan that returns a report given a config for this scan
 *
 * @author csmith, mcool
 */
public interface ICodeScanner extends IScanner<CodeScanConfig, CodeScanReport> {
	/**
	 * Return a report of this scan
	 *
	 * @param config the config to provide info for the scan
	 * @return the report generated by this scan, never null
	 */
	CodeScanReport scan(CodeScanConfig config);

	/**
	 * Get the rule class that this scanner supports
	 * 
	 * @return the {@link RuleDto} rule class that this scanner can handle
	 */
	Class<? extends RuleDto> getSupportedRuleClass();

}
