package com.tracelink.appsec.watchtower.core.module.scanner;

import org.springframework.stereotype.Component;

import com.tracelink.appsec.watchtower.core.report.ScanReport;
import com.tracelink.appsec.watchtower.core.rule.RuleDto;

/**
 * The executor of a scan that returns a report given a config for this scan
 *
 * @author csmith, mcool
 */
@Component
public interface IScanner<C> {
	/**
	 * Return a report of this scan
	 *
	 * @param config the config to provide info for the scan
	 * @return the report generated by this scan, never null
	 */
	ScanReport scan(C config);

	/**
	 * Get the rule class that this scanner supports
	 * 
	 * @return the {@link RuleDto} rule class that this scanner can handle
	 */
	Class<? extends RuleDto> getSupportedRuleClass();

	Class<C> getSupportedConfigClass();
}
